apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - host: "devopstn.com"
    http:
      paths:
      - path: /haykel
        pathType: ImplementationSpecific
        backend:
          service:
            name: hayhay
            port:
              number: 8085
