apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-hay
  namespace: haykel
  annotations:
      ingress.class: haproxy
  
spec:
  
  rules:
  - host: devopstn.tn
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-boot-app-service
            port:
              number: 80
