apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - host: "devopstn.com"
    http:
      paths:
      - path: /haykel
        pathType: Prefix
        backend:
          service:
            name: hayhay
            port:
              number: 3333
