apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hh-ingress
spec:
  rules:
  - host: 'http://devopstn.com'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hayhay
            port:
              number: 8085
