ingress:
  enabled: true
  annotations:
    # Add any annotations you need for your Ingress controller
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: devopstn.com
      paths:
        - /
  pathType: Prefix
  service:
    name: spring-boot-app-service
    port: 80
