apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-hay
  namespace: haykel
  
spec:
  ingressClassName: nginx
  rules:
  - host: http://devopstn.com
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-boot-app-service
            port:
              number: 8080
