apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hhyaz-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: devopstn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hayhay
            port:
              number: 808
